openapi: 3.0.3
info:
  title: Blizzard API
  version: 0.2.1
  description: An OpenAPI specification for Blizzard API
servers:
  - url: https://{region}.api.blizzard.com
    variables:
      region:
        description: API data is limited to specific regions
        default: eu
        enum:
          - eu
          - us
          - kr
          - tw
tags:
  - name: Playable Race API
  - name: Playable Class API
  - name: Playable Specialization API
security:
  - accessToken: []
paths:
  /data/wow/playable-class/index:
    get:
      tags:
        - Playable Class API
      summary: Returns an index of playable races.
      operationId: getPlayableClassesIndex
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableClassesIndexDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
  /data/wow/playable-class/{classId}:
    get:
      tags:
        - Playable Class API
      summary: Returns a playable class by ID.
      operationId: getPlayableClass
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
        - in: path
          name: classId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableClassDetailsDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
  /data/wow/playable-race/index:
    get:
      tags:
        - Playable Race API
      summary: Returns an index of playable races.
      operationId: getPlayableRacesIndex
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableRacesIndexDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
  /data/wow/playable-race/{playableRaceId}:
    get:
      tags:
        - Playable Race API
      summary: Returns a playable race by ID.
      operationId: getPlayableRace
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
        - in: path
          name: playableRaceId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableRaceDetailsDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
  /data/wow/playable-specialization/index:
    get:
      tags:
        - Playable Specialization API
      summary: Returns an index of playable specializations.
      operationId: getPlayableSpecializationsIndex
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableSpecializationIndexDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
  /data/wow/playable-specialization/{specId}:
    get:
      tags:
        - Playable Specialization API
      summary: Returns a playable race by ID.
      operationId: getPlayableSpecialization
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
            default: static-eu
          required: true
        - in: path
          name: specId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Http 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayableSpecializationDetailsDTO'
        4XX:
          description: Http 4XX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorDTO'
components:
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
  schemas:
    ApiErrorDTO:
      type: object
      properties:
        code:
          type: integer
        type:
          type: string
        detail:
          type: string
      required:
        - code
        - type
        - detail
    NameDataDTO:
      type: object
      properties:
        en_US:
          type: string
        es_MX:
          type: string
        pt_BR:
          type: string
        de_DE:
          type: string
        en_GB:
          type: string
        es_ES:
          type: string
        fr_FR:
          type: string
        it_IT:
          type: string
        ru_RU:
          type: string
        ko_KR:
          type: string
        zh_TW:
          type: string
        zh_CN:
          type: string
      required:
        - en_US
        - es_MX
        - pt_BR
        - de_DE
        - en_GB
        - es_ES
        - fr_FR
        - it_IT
        - ru_RU
        - ko_KR
        - zh_TW
        - zh_CN
    IndexDataDTO:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/NameDataDTO'
        id:
          type: integer
      required:
        - name
        - id
    IndexDataWithoutIdDTO:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/NameDataDTO'
      required:
        - name
    GenderDTO:
      type: object
      properties:
        male:
          $ref: '#/components/schemas/NameDataDTO'
        female:
          $ref: '#/components/schemas/NameDataDTO'
      required:
        - male
        - female
    PlayableRacesIndexDTO:
      type: object
      properties:
        races:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
      required:
        - races
    PlayableClassesIndexDTO:
      type: object
      properties:
        classes:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
      required:
        - classes
    PlayableSpecializationIndexDTO:
      type: object
      properties:
        character_specializations:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
        pet_specializations:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
      required:
        - character_specializations
        - pet_specializations
    FactionPlayableRaceDTO:
      type: object
      properties:
        type:
          type: string
        name:
          $ref: '#/components/schemas/NameDataDTO'
      required:
        - type
        - name
    PlayableRaceDetailsDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          $ref: '#/components/schemas/NameDataDTO'
        gender_name:
          $ref: '#/components/schemas/GenderDTO'
        faction:
          $ref: '#/components/schemas/FactionPlayableRaceDTO'
        is_selectable:
          type: boolean
        is_allied_race:
          type: boolean
        playable_classes:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
      required:
        - id
        - name
        - gender_name
        - faction
        - is_selectable
        - is_allied_race
        - playable_classes
    PlayableClassDetailsDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          $ref: '#/components/schemas/NameDataDTO'
        gender_name:
          $ref: '#/components/schemas/GenderDTO'
        power_type:
          $ref: '#/components/schemas/NameDataDTO'
        specializations:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
        playable_races:
          type: array
          items:
            $ref: '#/components/schemas/IndexDataDTO'
      required:
        - id
        - name
        - gender_name
        - power_type
        - specializations
        - playable_races
    RoleIndexDTO:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/NameDataDTO'
        type:
          type: string
      required:
        - name
        - type
    TalentIndexDTO:
      type: object
      properties:
        talent:
          $ref: '#/components/schemas/IndexDataDTO'
        spell_tooltip:
          $ref: '#/components/schemas/TalentDescritpionIndexDTO'
      required:
        - talent
        - spell_tooltip
    TalentDescritpionIndexDTO:
      type: object
      properties:
        description:
          $ref: '#/components/schemas/NameDataDTO'
        cast_time:
          $ref: '#/components/schemas/NameDataDTO'
      required:
        - description
        - cast_time
    PlayableSpecializationDetailsDTO:
      type: object
      properties:
        id:
          type: integer
        playable_class:
          $ref: '#/components/schemas/IndexDataDTO'
        name:
          $ref: '#/components/schemas/NameDataDTO'
        gender_description:
          $ref: '#/components/schemas/GenderDTO'
        role:
          $ref: '#/components/schemas/RoleIndexDTO'
        pvp_talents:
          type: array
          items:
            $ref: '#/components/schemas/TalentIndexDTO'
        spec_talent_tree:
          $ref: '#/components/schemas/IndexDataWithoutIdDTO'
        power_type:
          $ref: '#/components/schemas/IndexDataDTO'
        primary_stat_type:
          $ref: '#/components/schemas/RoleIndexDTO'
      required:
        - id
        - playable_class
        - name
        - gender_description
        - role
        - pvp_talents
        - power_type
        - primary_stat_type
