name: Develop CI
on:
  release:
    types: [released]
jobs:
  generate_openapi:
    runs-on: ubuntu-22.04
    container:
      image: openapitools/openapi-generator-cli:v7.2.0
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Generate java client
        run: docker-entrypoint.sh generate
          -i openapi.yaml
          -g java
          -o generated/java
          --api-package=com.blizzardapi.openapi
          --additional-properties=disallowAdditionalPropertiesIfNotPresent=false
          --additional-properties=groupId=com.blizzardapi
          --additional-properties=artifactId=openapi
          --model-package=com.blizzardapi.openapi.model
          --additional-properties=dateLibrary=java8
          --additional-properties=hideGenerationTimestamp=true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
  build-package-deploy-java:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{hashFiles('generated/java/pom.xml')}}
          restore-keys: ${{ runner.os }}-maven-
      - name: Deploy java part
        run: mvn -B clean deploy -f generated/java/pom.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/jbwittner/blizzard_openapi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}