name: Develop CI
on:
  release:
    types: [released]
env:
  REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  build-package-java:
    runs-on: ubuntu-22.04
    needs:
      - check_generation
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('generated/java/pom.xm') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install java part
        run: mvn -B clean deploy -f generated/java/pom.xml